name: Bot
description: 

globals:
  attributes:
    - id: value__0_v_out
      label: "keys"
      type: string[]
      value: ["w", "a", "s", "d"]
      description: "Static attribute: keys"
    - id: value__1_v_out
      label: "Value"
      type: int
      value: 4
      description: "Static attribute: Value"
